# Generated by Django 4.2.9 on 2024-02-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_objects',
            new_name='user_object',
        ),
    ]
